spring:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  datasource:
   url: jdbc:mysql://localhost:3306/market?useSSL=false
   username: root
   password: 123456
  flyway:
    baseline-on-migrate: true
