spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
  datasource:
   url: jdbc:mysql://localhost:3306/segomarket?useSSL=false
   username: root
   password: 123456
  flyway:
    baseline-on-migrate: true


